import env from '@/core/config/env';

const PARAMETERS = {
  APP_NAME: env.appName,
  SERVER_URL: env.serverUrl,
  DATA_EDITOR_BASE_PATH: env.dataEditorBaseUrl,
  PROJECT_HOME_PATH: '/project/',
  PROJECT_LOGO_QUERY_STRING: '?type=photo&name=logo.jpg&format=project_mobile_logo',
  DATA_VIEWER_PATH: '/data',
  DATA_EDITOR_ADD_ENTRY_PATH: '/add-entry',
  DATA_EDITOR_EDIT_ENTRY_PATH: '/edit-entry',
  TABLE_FIXED_HEADERS_TITLE_INDEX: 4,
  TABLE_FIXED_HEADERS_CHILDREN_INDEX: 3,
  TABLE_FIXED_HEADERS_TOTAL: 6,
  TABLE_FIXED_HEADERS_CREATED_AT_INDEX: 5,
  API_PROJECT_ENDPOINT: '/api/internal/project/',
  API_MEDIA_ENDPOINT: '/api/internal/media/',
  API_ENTRIES_ENDPOINT: '/api/internal/entries/',
  API_ENTRIES_LOCATIONS_ENDPOINT: '/api/internal/entries-locations/',
  API_DOWNLOAD_ENDPOINT: '/api/internal/download-entries/',
  API_DOWNLOAD_MEDIA_ENDPOINT: '/api/internal/download-media/',
  API_UPLOAD_TEMPLATE_ENDPOINT: '/api/internal/upload-template/',
  API_UPLOAD_HEADERS_ENDPOINT: '/api/internal/upload-headers/',
  API_DOWNLOAD_SUBSET_ENDPOINT: '/api/internal/download-entries-subset/',
  API_UPLOAD_INTERNAL_ENDPOINT: '/api/internal/web-upload/',
  API_BULK_UPLOAD_INTERNAL_ENDPOINT: '/api/internal/bulk-upload/',
  API_UPLOAD_EXTERNAL_ENDPOINT: '/api/upload/',
  API_BULK_UPLOAD_EXTERNAL_ENDPOINT: '/api/bulk-upload/',
  API_DELETION_ENDPOINT: '/api/internal/deletion/entry/',
  IMAGES_PATH_LARAVEL: '/images/',
  MAX_TITLE_LENGHT: 20,
  TABLE_UPLOAD_PER_PAGE: 25,
  TABLE_UPLOAD_MAX_ROWS: 150,
  BULK_MAX_FILE_SIZE_BYTES: 1000000,
  FORMAT_CSV: 'csv',
  DEFAULT_ORDERING_COLUMN: 'created_at',
  DEFAULT_ORDERING: 'DESC',
  ORDER_BY: {
    NEWEST: 'Newest',
    OLDEST: 'Oldest',
    AZ: 'A - Z',
    ZA: 'Z - A'
  },
  INPUT_TYPES: {
    EC5_TEXT_TYPE: 'text',
    EC5_PHONE_TYPE: 'phone',
    EC5_TEXTAREA_TYPE: 'textarea',
    EC5_INTEGER_TYPE: 'integer',
    EC5_DECIMAL_TYPE: 'decimal',
    EC5_DATE_TYPE: 'date',
    EC5_TIME_TYPE: 'time',
    EC5_RADIO_TYPE: 'radio',
    EC5_CHECKBOX_TYPE: 'checkbox',
    EC5_DROPDOWN_TYPE: 'dropdown',
    EC5_BARCODE_TYPE: 'barcode',
    EC5_LOCATION_TYPE: 'location',
    EC5_AUDIO_TYPE: 'audio',
    EC5_VIDEO_TYPE: 'video',
    EC5_PHOTO_TYPE: 'photo',
    EC5_BRANCH_TYPE: 'branch',
    EC5_GROUP_TYPE: 'group',
    EC5_README_TYPE: 'readme',
    EC5_SEARCH_SINGLE_TYPE: 'searchsingle',
    EC5_SEARCH_MULTIPLE_TYPE: 'searchmultiple',
    EC5_DATASET_SINGLE_TYPE: 'dataset single',
    EC5_DATASET_MULTIPLE_TYPE: 'dataset multiple'
  },
  BULK_UPLOADABLE_TYPES: [
    'text',
    'phone',
    'textarea',
    'integer',
    'decimal',
    'date',
    'time',
    'radio',
    'checkbox',
    'dropdown',
    'barcode',
    'location',
    'searchsingle',
    'searchmultiple'
  ],
  CEll_TYPES: {
    BRANCH: 'CellBranch',
    CHILDREN: 'CellChildren',
    MEDIA: 'CellMedia',
    TEXT: 'CellText'
  },
  MULTIPLE_ANSWERS_TYPES: ['radio', 'checkbox', 'dropdown', 'searchsingle', 'searchmultiple'],
  MULTIPLE_ANSWERS_TYPES_AS_ARRAY: ['checkbox', 'searchsingle', 'searchmultiple'],
  MEDIA_TYPES: ['audio', 'photo', 'video'],
  DATE_FORMAT_1: 'dd/MM/YYYY',
  DATE_FORMAT_2: 'MM/dd/YYYY',
  DATE_FORMAT_3: 'YYYY/MM/dd',
  DATE_FORMAT_4: 'MM/YYYY',
  DATE_FORMAT_5: 'dd/MM',
  TIME_FORMAT_1: 'HH:mm:ss',
  TIME_FORMAT_2: 'hh:mm:ss',
  TIME_FORMAT_3: 'HH:mm',
  TIME_FORMAT_4: 'hh:mm',
  TIME_FORMAT_5: 'mm:ss',
  TIMEFRAME: {
    LIFETIME: 'Lifetime',
    TODAY: 'Today',
    LAST_7_DAYS: 'Last 7 days',
    LAST_30_DAYS: 'Last 30 days',
    YEAR: 'Current year',
    CUSTOM: 'Custom'
  },
  COOKIES: {
    DOWNLOAD_ENTRIES: 'epicollect5-download-entries'
  },
  LABELS: {
    FILE_UPLOAD_ERROR: 'Invalid file',
    FILE_UPLOAD_ERROR_NO_ROWS: 'Invalid file, no entries found',
    FILE_SIZE_ERROR: 'File size exceeded',
    FILE_MAPPING_ERROR: 'File mapping does not match'
  }
};

export default PARAMETERS;
